# Generated by Django 5.0.3 on 2024-03-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('pi_id', models.FloatField(primary_key=True, serialize=False)),
                ('pi_name', models.TextField()),
                ('pi_age', models.IntegerField()),
                ('pi_gender', models.TextField()),
            ],
            options={
                'db_table': 'patient_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VitalInfo',
            fields=[
                ('vi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vi_bp', models.FloatField()),
                ('vi_bsl', models.FloatField()),
                ('vi_weight', models.FloatField()),
                ('vi_hieght', models.FloatField()),
                ('vi_temp', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'vital_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='SympDisease',
        ),
    ]
