# Generated by Django 5.0.3 on 2024-03-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_patientinfo_vitalinfo_delete_info_delete_sympdisease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalinfo',
            options={'managed': True},
        ),
    ]
