# Generated by Django 5.0.3 on 2024-03-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_vitalinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalinfo',
            name='Disease',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalinfo',
            name='aadhar',
            field=models.OneToOneField(db_column='aadhar', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.patientinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalinfo',
            name='vi_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
